#!/usr/bin/env bash  

IP=$1
JOBID=$2
PREVID=$3
IMAGE=$4

pfconclient http://$IP/api/v1/ $JOBID run \
--cmd_args "--saveinputmeta --saveoutputmeta --convertOnlySingleDICOM --inputFile $IMAGE" \
--auid developer --number_of_workers 1 --cpu_limit 4000 --memory_limit 4000 --gpu_limit 0 \
--image fnndsc/pl-med2img --selfexec med2img \
--selfpath /usr/local/bin --execshell python3 --type ds /tmp/$PREVID /tmp/$JOBID
