#!/usr/bin/env bash  

IP=$1
JOBID=$2
PREVID=$3

pfconclient http://$IP/api/v1/ $JOBID run \
--cmd_args "--saveinputmeta --saveoutputmeta --imagefile sample.png" \
--auid developer --number_of_workers 1 --cpu_limit 1000 --memory_limit 500 --gpu_limit 0 \
--image fnndsc/pl-covidnet --selfexec covidnet \
--selfpath /usr/local/bin --execshell python3 --type ds /tmp/$PREVID /tmp/$JOBID
