#!/usr/bin/env bash                                                                                                                                                     

JOBID=$1
IP=$2
SERVICE=$3
IMAGE=$4

pfurl --verb POST --raw --http $IP/api/v1/cmd --jsonwrapper 'payload' --msg \
          '{   "action": "run",
               "meta":  {
                    "cmd":      "python simpledsapp.py --prefix test- --sleepLength 0 /share/incoming /share/outgoing",
                    "auid": "rudolphpienaar",
                    "jid":      "'$JOBID'",
                    "threaded": true,
                    "container": {
                         "target": {
                                "image": "'${IMAGE:-fnndsc/pl-simpledsapp}'"
                              },
                          "manager": {
                                "image":        "fnndsc/swarm",
                                "app":          "swarm.py",
                                "env":  {
                                    "shareDir":     "/tmp",
                                    "serviceType":  "docker",
                                    "serviceName":  "'$SERVICE'"
                                }
                          }
                          }
                }
           }' --quiet --jsonpprintindent 4



