#!/usr/bin/env bash

IP=$1
JOBID=$2




http POST $IP/api/v1/ json=\
'{ "auid": "samal.s@husky.neu.edu",
    "cmd_args": "--saveinputmeta --saveoutputmeta --dir cube/uploads",
    "cmd_path_flags": "--dir",
    "cpu_limit": "4000M",
    "execshell": "/usr/local/bin/python",
    "gpu_limit": "0",
    "image": "fnndsc/pl-dircopy",
    "jid": "'$JOBID'",
    "memory_limit": "4000Mi",
    "number_of_workers": "1",
    "selfexec": "dircopy", 
    "selfpath": "/usr/local/bin", 
    "type": "fs"
}'

